# This file was generated by GoReleaser. DO NOT EDIT.
cask "gox" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_x86_64.zip"
      sha256 "9ddc29b41a51defa9394947f17d5116b00bd5dca71189154045df9d5bc56cba5"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_arm64.zip"
      sha256 "245f0d140f14171e3c693f0ea0472c49988c68f0b37c713b1e765c4255665c9f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_x86_64.tar.gz"
      sha256 "82842ceee79f5a3209ece593d0e735707a32ba7010c2323ab1a8bfcf7041eeab"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_arm64.tar.gz"
      sha256 "d687559f49000dc159bc2d1820e7b4e0efbea6e811f529a1c56d1185ca6ce30a"
    end
  end

  name "gox"
  desc "Go version of npx - Execute Go binaries directly from source"
  homepage "https://github.com/suapapa/gox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gox"

  # No zap stanza required

end
