# This file was generated by GoReleaser. DO NOT EDIT.
cask "gox" do
  version "0.3.11"

  on_macos do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_x86_64.zip"
      sha256 "8f6d7aacb1bf9fdd0bc930784834c109b675ff1c64f697049c66ca1ce6769548"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_arm64.zip"
      sha256 "32dd34d9c5b19e743610d955f76e65438fbd375a0a9f43b8d6e3dd790521284f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_x86_64.tar.gz"
      sha256 "5b797f8cc8e30fc16caeec82f35747c67097c1632f377e1d10b9e37b3d6e3ce3"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_arm64.tar.gz"
      sha256 "b16e9231a42f47af1b3f05b090347aa064b796c017e28a446a7e0491dfc7cc62"
    end
  end

  name "gox"
  desc "Go version of npx - Execute Go binaries directly from source"
  homepage "https://github.com/suapapa/gox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gox"

  # No zap stanza required

end
