# This file was generated by GoReleaser. DO NOT EDIT.
cask "gox" do
  version "0.3.12"

  on_macos do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_x86_64.zip"
      sha256 "2db35d32c598c91390f7fead15854949a7e2bbdb14c5822ea4af742a1ef10a1d"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Darwin_arm64.zip"
      sha256 "2f164baec7a4072ff83bfd837f31a7dc61e4a823c53bcdf9efc5d66e2bb6225e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_x86_64.tar.gz"
      sha256 "8d6778d5be5cb27d4809ab8c70d86711aaecaabe109f1a3ec647e4f54b51e56b"
    end
    on_arm do
      url "https://github.com/suapapa/gox/releases/download/v#{version}/gox_Linux_arm64.tar.gz"
      sha256 "39bd33bfcec3ea53cf357e191080e04172220bdcd234f118aad5af4c233adf05"
    end
  end

  name "gox"
  desc "Go version of npx - Execute Go binaries directly from source"
  homepage "https://github.com/suapapa/gox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gox"

  # No zap stanza required

end
