# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gox < Formula
  desc "Go version of npx - Execute Go binaries directly from source"
  homepage "https://github.com/suapapa/gox"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suapapa/gox/releases/download/v0.1.1/gox_Darwin_x86_64.tar.gz"
      sha256 "cae7f75346c8eed796bfec8dd0347f9c15a214a242e4fe671066488a6fc907ef"

      define_method(:install) do
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suapapa/gox/releases/download/v0.1.1/gox_Darwin_arm64.tar.gz"
      sha256 "fda908a5920a82fec9b29b9a21e5fa45c4c397d29d19b683be5b0ef784587396"

      define_method(:install) do
        bin.install "gox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suapapa/gox/releases/download/v0.1.1/gox_Linux_x86_64.tar.gz"
      sha256 "1a9dcc0f939a5eeb59fdff55e8d4b9447e110f326916193cfd51248e2b57ee1b"
      define_method(:install) do
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suapapa/gox/releases/download/v0.1.1/gox_Linux_arm64.tar.gz"
      sha256 "4fb0b7290e111c3cd56ad4a5abb0c326dd949ff4ca473cb19435e8e12de1bf15"
      define_method(:install) do
        bin.install "gox"
      end
    end
  end

  test do
    system "#{bin}/gox help"
  end
end
