# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gox < Formula
  desc "Go version of npx - Execute Go binaries directly from source"
  homepage "https://github.com/suapapa/gox"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suapapa/gox/releases/download/v0.1.2/gox_Darwin_x86_64.tar.gz"
      sha256 "95af51b1bffb95eb0bf5f86954adedef675fcb6b61ff8b8894a66fd0f9af4c07"

      define_method(:install) do
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suapapa/gox/releases/download/v0.1.2/gox_Darwin_arm64.tar.gz"
      sha256 "c0fb6262a7653a29fc21e5f76d47e9f0b8955c31029dbfcffedd6cf82f7e4c37"

      define_method(:install) do
        bin.install "gox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suapapa/gox/releases/download/v0.1.2/gox_Linux_x86_64.tar.gz"
      sha256 "1da229ce26a2da05e7380012dc1c01f60d32e6bf8262f1ab189c9e0c8f1a359c"
      define_method(:install) do
        bin.install "gox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suapapa/gox/releases/download/v0.1.2/gox_Linux_arm64.tar.gz"
      sha256 "906a1e61befbf5d31af299319cafc8f8495b5300f1756ca7f94ab1c6d083f7ca"
      define_method(:install) do
        bin.install "gox"
      end
    end
  end

  test do
    system "#{bin}/gox help"
  end
end
